
.git/
pix2code
sketch-code
sketch-code/data
sketch-code/bin
pix2code/datasets
*.pyc
inference/node_modules/*
detection/src/clf/training_data/
detection/src/clf/testing/
detection/src/clf/training/
detection/src/clf/squiggle_legacy/
inference/.cache
inference/output/*detection/clf/squiggle_legacy
.DS_Store
web-platform/.uploads/*
web-platform/node_modules/*
web-platform/.generated/*
web-platform/.cache/*
.output/
.cache
inference/.*

detection/src/clf/PrimitiveDetect/darknet-yolo
detection/src/clf/PrimitiveDetect/data
detection/src/clf/PrimitiveDetect/.git
detection/src/pyweb/
